import os

DB_USER = os.environ["DB_USER"]
DB_PASSWORD = os.environ["DB_PASSWORD"]
DB_NAME = os.environ["DB_NAME"]
DB_HOST = os.environ["DB_HOST"]
DB_PORT = int(os.environ["DB_PORT"])

SERVER_API_HOST = os.environ["SERVER_API_HOST"]
SERVER_API_PORT = int(os.environ["SERVER_API_PORT"])

S3_BUCKET_NAME = os.environ["S3_BUCKET_NAME"]

MIN_NUMBER_OF_INSTALLS_FOR_TRAINING = int(
    os.environ.get("MIN_NUMBER_OF_INSTALLS_FOR_TRAINING", "3000")
)
MIN_NUMBER_OF_TARGET_USERS_FOR_TRAINING = int(
    os.environ.get("MIN_NUMBER_OF_TARGET_USERS_FOR_TRAINING", "500")
)

NUMBER_OF_EVENTS_TO_PROCESS_PER_FIT_ITERATION = int(
    os.environ.get("NUMBER_OF_EVENTS_TO_PROCESS_PER_FIT_ITERATION", "1000000")
)
NUMBER_OF_EVENTS_TO_PROCESS_PER_INFERENCE_ITERATION = int(
    os.environ.get("NUMBER_OF_EVENTS_TO_PROCESS_PER_INFERENCE_ITERATION", "10000000")
)
